language: node_js

node_js:
  - 'stable'

sudo: false

matrix:
  fast_finish: true

branches:
  only:
  - master

install:
  - npm install -g tspack
  - npm install
  - npm update

script:
  - cd src
  - tspack

cache:
  directories:
    - node_modules

git:
  depth: 1

notifications:
  email: false